name: Deploy Workflow

inputs:
  environment:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4.1.7

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.7
    - name: Terraform Init
      run: |
        terraform -chdir=infrastructure/${{ inputs.environment }} init
        terraform -chdir=infrastructure/${{ inputs.environment }} validate
        terraform -chdir=infrastructure/${{ inputs.environment }} plan -out "planfile"
        terraform -chdir=infrastructure/${{ inputs.environment }} apply -input=false "planfile"
      shell: bash
